CXXFLAGS=-I..

all:map_test.exe vector_test.exe set_test.exe

map_test.exe:map_test.cpp
	$(CXX) $(CXXFLAGS) map_test.cpp -o map_test.exe
	
vector_test.exe:vector_test.cpp
	$(CXX) $(CXXFLAGS) vector_test.cpp -o vector_test.exe

set_test.exe:set_test.cpp
	$(CXX) $(CXXFLAGS) set_test.cpp -o set_test.exe
